services:
  mariadb:
    image: mariadb:11.4
    container_name: arab_mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: arab
      MARIADB_PASSWORD: arab
      MARIADB_DATABASE: arab
    volumes:
      - mysql:/var/lib/mysql:rw

  webserver:
    restart: unless-stopped
    container_name: arab_webserver
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - ./static:/webserver/static:ro
      - ./templates:/webserver/templates:ro
    build:
      context: ./webserver/
      dockerfile: Dockerfile
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  mysql: