services:
  mariadb:
    image: mariadb:11.4
    container_name: arab_mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: arab
      MARIADB_PASSWORD: arab
      MARIADB_DATABASE: arab
    volumes:
      - mysql:/var/lib/mysql:rw

  nginx:
    image: nginx:latest
    container_name: arab_nginx
    restart: unless-stopped
    depends_on:
      - webserver
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/akos/ssl/akos60.dev/cloudflare.crt:/etc/nginx/ssl/cloudflare.crt:ro
      - /home/akos/ssl/akos60.dev/cloudflare.key:/etc/nginx/ssl/cloudflare.key:ro

  webserver:
    restart: unless-stopped
    container_name: arab_webserver
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - logs:/webserver/logs:rw
      - ./static:/webserver/static:ro
      - ./templates:/webserver/templates:ro
    build:
      context: ./webserver/
      dockerfile: Dockerfile
    
volumes:
  logs:
  mysql: